spring:
    application:
        name: service-eureka

server:
    port: 8762

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        service-url:
            defaultZone: http://localhost:8762/eureka/
    server:
        enable-self-preservation: false
